volumes:
  postgres-data:
    external: true
  # other volumes...
services:
  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=users,letters
      - POSTGRES_PASSWORD=password
    ports:
      - 15432:5432
  users_service:
    build:
      context: ./users_service
      dockerfile: ./Dockerfile.dev
    ports:
      - 8080:8000
    volumes:
      - ./users_service:/app
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      USERS_DATABASE_URL: ${USERS_DATABASE_URL}
      WAIT_HOSTS: postgres:5432
  letters_service:
    build:
      context: ./letters_service
      dockerfile: ./Dockerfile.dev
    ports:
      - 8090:8000
    volumes:
      - ./letters_service:/app
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      LETTERS_DATABASE_URL: ${LETTERS_DATABASE_URL}
      WAIT_HOSTS: postgres:5432
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_CIVICS_KEY: ${GOOGLE_CIVICS_KEY}
      OPENAI_URL: ${OPENAI_URL}
      GOOGLE_CIVICS_URL: ${GOOGLE_CIVICS_URL}
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      SIGNING_KEY: 7ea8f8c1d636b6f92b59a46326d9f59da1e09f0c986fbaeacaad64fed817ce6d
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
      REACT_APP_USERS_API_HOST: http://localhost:8080
      REACT_APP_LETTERS_API_HOST: http://localhost:8090
